const fs = require('fs');

const rawData = `ABRAZADERA COLLARIN PE 110 MM X 3"
ABRAZADERA COLLARIN PE 50 MM X 1/2"
ABRAZADERA COLLARIN PE 63 MM X 1 1/2" PN 12.5
ABRAZADERA COLLARIN PE 90 MM X 2" PN 12.5
ABRAZADERA DE 4" X 2"
ABRAZADERA DE 4" X 3"
ABRAZADERA UNISTRAI DE 1 1/2"
ADAPTADOR 220-110 VOL HURRICANE
ADAPTADOR DE 1 1/2" PVC
ADAPTADOR DE 1 1/4" PVC
ADAPTADOR DE 1" PVC
ADAPTADOR DE 1/2" PVC
ADAPTADOR DE 2 1/2" PVC
ADAPTADOR DE 2" PVC
ADAPTADOR DE 3" PVC
ADAPTADOR DE 3/4" PVC
ADAPTADOR DE 50 W
ADAPTADOR PE  32 MM X 1"
ADAPTADOR PE 20 MM X 1/2"
ADAPTADOR PE 25 MM X 3/4"
ADAPTADOR PE DE 16 MM X 1/2"
ADAPTADOR PE DE 16 MM X 3/4"
ADAPTADOR PE DE 20 MM X 1/2"
ADAPTADOR PE DE 20 MM X 3/4"
ADAPTADOR PE DE 25 MM X 3/4"
ADOQUIN NEGRO DE 20 X 10 X 4 CM
ARENA DE CUARZO 1/16"
ARENA DE CUARZO 1/32"
ARENA DE CUARZO 1/8" SACO X 40 GR
ASPERSOR DE IMPACTO DE 1" MOD: 7025RD-I-1"M - SENNINGER
ASPERSOR DE IMPACTO DE 1/2" (9°) MOD: 2009HS-I-1/2"M -SENNINGER
ASPERSOR DE IMPACTO DE 3/4" (12°) MOD: 2023HBS-I-3/4"M -SENNINGER
ASPERSOR DE IMPACTO DE CÍRCULO PARCIAL DE 3/4" (23°) MOD: 3123PC-I-3/4" M BOQ. 9 - SENNINGER
ASPERSOR DE NO IMPACTO SMOOTH DRIVE (BLANCO) MOD: SD2214M-2M ANGULO BAJO - SENNINGER
ASPERSOR JOLLY ALUMINIO DE 1 1/4" SIME PART
ASPERSOR VYR 802 SECTORIAL PLÁSTICO 1/2"
ASPIRADORA PROVAC 214-R201276 PESADA SOPORTE DE EMTAL CON 8 RUEDAS
AUTOMÁTICO DE NIVEL "LUISE" GL90 CABLE DE NEOPRENO
AUTOMÁTICO DE NIVEL "ROTOPLAST"
AUTOMÁTICO DE PRESIÓN "SQUARE-D" FSG-2 (HASTA 80 PSI)
AUTOMÁTICO DE PRESIÓN ESPA PRESSDRIVE AM NP
BALDE DE CLORO EN PASTILLAS
BALDE DE CLORO GRANULADO
BASE DE 8 PINES
BASE DE ALUMINIO PORTA ASPERSOR VYR 2000
BASE PARA BOQUILLA SP1022S
BASE PARA RELEI
BATERIA DE 9 V
BOLSA ARENA FINA
BOLSA ARENA GRUESA
BOLSA CEMENTO
BOLSA YESO
BOQ 10 A REGULABLE DE 0° A 360° RAIN BIRD
BOQ 10 VAN REGULABLE DE 0° A 360° RAIN BIRD
BOQ 12 A REGULABLE DE 0° A 360° RAIN BIRD
BOQ 15 VAN REGULABLE DE 0° A 360°  RAIN BIRD
BOQ 4 A REGULABLE DE 0° A 360° RAIN BIRD
BOQ 6 A REGULABLE DE 0° A 360° RAIN BIRD
BOQ 8 A REGULABLE DE 0° A 360° RAIN BIRD
BOQ ARCO REGULABLE 20°-360° AA10  (AA10-M)MACHO HIT
BOQ ARCO REGULABLE 20°-360° AA12  (AA12-M)MACHO HIT
BOQ DE TRAYECTRIA POR FRANJAS CS-530 - HUNTER
BOQ DE TRAYECTRIA POR FRANJAS ES-515 - HUNTER
BOQ DE TRAYECTRIA POR FRANJAS SS-530 - HUNTER
BOQ DIRECCIONAL DE 1 1/2" CON BASE
BOQ FIJA ESPECIAL 15CST - RAIN BIRD
BOQ FIJA ESPECIAL 15EST - RAIN BIRD
BOQ FIJA ESPECIAL 15SST - RAIN BIRD
BOQ FIJA PATRÓN ESPECIAL 15CST - M501-134 - HIT
BOQ FIJA PATRÓN ESPECIAL 15EST - M501-133 - HIT
BOQ FIJA PATRÓN ESPECIAL 15SST4 - M501-131 - HIT
BOQ FIJA PATRÓN ESPECIAL 17SST9 - M501-132 - HIT
BOQ MACHO DE ARCO FIJO 180° PATRÓN ESPECIAL - 10HLA (M501-123) HIT
BOQ MACHO DE ARCO FIJO 180° PATRÓN ESPECIAL - 12H (M501-118) HIT
BOQ MACHO DE ARCO FIJO 180° PATRÓN ESPECIAL - 6FSG-LG (M501-129) HIT
BOQ MACHO DE ARCO FIJO 180° PATRÓN ESPECIAL - 8FSH (M501-126) HIT
BOQ MACHO DE ARCO FIJO 90° PATRÓN ESPECIAL - 10QLA (M501-122) HIT
BOQ MACHO DE ARCO FIJO 90° PATRÓN ESPECIAL - 12Q (M501-116) HIT
BOQ MACHO DE ARCO FIJO 90° PATRÓN ESPECIAL - 6FSQ-LG (M501-128)  HIT
BOQ MACHO DE ARCO FIJO 90° PATRÓN ESPECIAL - 8FSQ (M501-125) HIT
BOQUILLA NEGRA (130 LPH) DE MICROASPERSOR
BRIDA DE FIERRO ROSCADA DE 2" X 150 LBS
BRIDA LOCA PVC 2" CON BUJE 2" SP, INY PN 10
BRIDA ROSCADA TIPO ANILLO 150 LBS C-4 DE 3"
BRIDA ROSCADA TIPO ANILLO 150LBS C-40 2"
BROCA 1/32
BROCA 1/8
BROCA 5/16 PARA CONCRETO
BROCA DE 1 1/2"
BUJE DE 2" X 1 1/2" -ERA
BUJE DE 2" X 1" = ERA
BUJE DE 3" X 2" - ERA
BUSHING DE 1 1/2" X 1 1/4" F/G
BUSHING DE 1 1/2" X 1 1/4" INOX
BUSHING DE 1 1/2" X 1" F/G
BUSHING DE 1 1/4" X 1"  INOX C-316 C/R
BUSHING DE 1" X 1/2" - PAVCO
BUSHING DE 1" X 1/2" INOX C-316 C/R
BUSHING DE 1" X 3/4" - PAVCO
BUSHING DE 1" X 3/4" - PVC
BUSHING DE 1/2" X 1/4"  
BUSHING DE 1/2" X 1/4" INOX C-316 C/R
BUSHING DE 2 1/2" X 2" F/G
BUSHING DE 2" X 1 1/2".
BUSHING DE 2" X 1 1/4" F/G
BUSHING DE 2" X 1" F/G
BUSHING DE 2" X 1" INOX C-316 C/R
BUSHING DE 2" X 1/2" INOX-304 C/R
BUSHING DE 3" X 2" INOX C-316 C/R
BUSHING DE 3/4" X 1/2"
BUSHING DE 3/4" X 1/2"
BUSHING INOX C-316 C/R
BUSHING PE 3" X 2"
CABINETE HERMÉTICO ADOSABLE 45 X 30 X 20 POLICARBONATO
CABLE AUTOMOTRIZ N° 12 THW-90 12 AWG 750 V (CELSA)
CABLE AUTOMOTRIZ N° 18 TWF-80 18 AWG 750 V (CELSA)
CAJA
CAJA 30 X 30
CAJA 40 X 30 METAL
CAJA 8 POLOS
CAJA ADOSABLE DE 25 X 30
CAJA ADOSABLE PARA PARED CON PUERTA
CAJA DE 30 X 30 
CAJA DE 30 X 30 X 15 CM METAL
CAJA DE CINTA TEFLÓN
CAJA DE CONEXIÓN
CAJA DE DOBLE LLAVE
CAJA DE FULMINANTE
CAJA DE MASILLA
CAJA DE METAL
CAJA DE METAL 25 X 25
CAJA DE METAL 25 X 25
CAJA DE PASE PVC
CAJA GABINETE
CAJA GABINETE
CAJA GABINETE 25 X 25
CAJA GABINETE 30 X 20 CM
CAJA GABINETE DE 30 X 30
CAJA HERMÉTICA DE 30 X 25
CAJA METAL PARA ADOSAR
CAJA METÁLICA
CAJA PARA LLAVE DE 4 POLOS
CAJA PARA MEDIDOR
CAJA PARA MEDIDOR DE POLICARBONATO 108 RBA
CAJA PARA MEDIDOR Y TOMA
CAJA PORTA VÁLVULA RECTANGULAR 42 X 32 X 20 CM
CAJA PORTAVÁLVULA DE 7" MOD: VB-7BG - RAIN PRO
CAJA PORTAVÁLVULA DE RECTANGUAR DE 42 X 32 X 20 CM  - LAGO ABRISA
CAJA PORTAVÁLVULA RECTANGULAR 64 X 50 X 30 CM LAGO ABRISA 
CALAMINA DE COLOR BLANCO X 3.60
CANALETA 25 X 25 /RANURADO
CANASTILLA P/ELECTROBOMBA MAX FLO SPX1250RA HAYWARD
CANDADO DE 60 MM FORTE
CAÑO DE 1/2" CIMVAL
CAÑO DE 3/4"
CARTUCHO CX500RE MOD-C500 StarClear C-7656 HAYWARD
CASE GAMEMAX GAMING G505 BLACK/RED 1XUSB 3.0, 5XUSB 2.0 SIN FUENTE
CAUDALIMETRO RMW DE 2" WOLTMAN BRIDAD - RAPHAEL
CAUDALÍMETRO RWN WOLTMAN DE 2" W PULSO ANSI 125 BRIDADA
CAUDALÍMETRO TURBO-IR 50 MM 2" PULSO 100, C/BRIDA
CEMENTO QUISQUEYA ESTRUCTURAL
CINCEL EXAGONAL
CINTA AISLANTE - 3M
CINTA DE SEÑALIZACIÓN
CINTA TEFLÓN SHURTAPE 3/4" BLANCA 
CINTA VULCANIZANTE SCOTCH 23 3/4 X 9 MTS
CINTILLO 100 MM
CISTERNA RMA C 5000 LTS
CLORADOR EN LINEA CAP 09 PASTILLAS CL100
CODO D 3/4" S/P AGUA
CODO DE 1 1 /2" C/R AGUA PVC.
CODO DE 1 1/2" C/R AGUA
CODO DE 1 1/2" F/G
CODO DE 1 1/2" MIXTO AGUA PVC.
CODO DE 1 1/2" S/P
CODO DE 1 1/2" S/P AGUA
CODO DE 1 1/2" S/P AGUA
CODO DE 1 1/2" S/P AGUA
CODO DE 1 1/2" S/P AGUA
CODO DE 1 1/2" X 45° PVC
CODO DE 1 1/2" X 45° S/P AGUA
CODO DE 1 1/2" X 45° S/P AGUA
CODO DE 1" C/R AGUA
CODO DE 1" C/R AGUA PVC.
CODO DE 1" F/G
CODO DE 1" MIXTO AGUA PVC.
CODO DE 1" S/P AGUA
CODO DE 1" S/P AGUA
CODO DE 1" S/P AGUA
CODO DE 1" X 45° PVC
CODO DE 1" X 45° S/P AGUA
CODO DE 1" X 90° INOX C-316 C/R
CODO DE 1/2"  S/P AGUA
CODO DE 1/2" C/R AGUA 
CODO DE 1/2" C/R AGUA PVC.
CODO DE 1/2" MIXTO
CODO DE 1/2" MIXTO AGUA PVC.
CODO DE 1/2" S/P AGUA
CODO DE 1/2" S/P AGUA
CODO DE 1/2" S/P AGUA
CODO DE 1/2" S/P AGUA PVC.
CODO DE 1/2" X 45°
CODO DE 2" C/R AGUA PVC.
CODO DE 2" F/G
CODO DE 2" S/P AGUA
CODO DE 2" S/P AGUA
CODO DE 2" X 45° DESAGUE
CODO DE 2" X 45° PVC
CODO DE 2" X 90° C/R
CODO DE 2" X 90° DESAGUE
CODO DE 2" X 90° DESAGUE
CODO DE 2"C/R AGUA
CODO DE 3"  C/R  AGUA
CODO DE 3" C/R AGUA PVC.
CODO DE 3" S/P AGUA
CODO DE 3" S/P AGUA PVC.
CODO DE 3" X 90° S/P AGUA
CODO DE 3/4" C/R AGUA 
CODO DE 3/4" C/R AGUA PVC.
CODO DE 3/4" F/G
CODO DE 3/4" MIXTO AGUA PVC.
CODO DE 3/4" S/P AGUA
CODO DE 3/4" S/P AGUA
CODO DE 3/4" S/P AGUA PVC.
CODO DE 3/4" X 45° PVC
CODO DE 4" S/P AGUA
CODO DE 4" X 2" DESAGUE 
CODO DE 4" X 45° 
CODO DE 4" X 45° DESAGUE
CODO DE 4" X 90° DESAGUE
CODO DE 4" X 90° DESAGUE
CODO PE 20 X 20  DENTADA
CODO PE C/AZUL 32 MM X 1"
CODO PE C/AZUL 32 MM X 3/4"
CODO PE DE 1/2" X 16 MM DENTADA
CODO PE DE 16 MM DENTADA
CODO PE DE 20 MM DENTADA
CODO PE DE 25 MM DENTADA
CODO PE DE 25 MM X 3/4" C/AZUL
CODO PE DE 3/4" X 16 MM DENTADA
CODO PE DE 3/4" X 16 MM DENTADA
CODO PE DENTADO DE 1/2" X 16 MM
CODO PVC MIXTO DE 1/2"
COMANDO MOA
COMBA TRAMONTINA DE 3 LBS
COMBUSTIBLE
COMISIÓN
COMPRESOR
CONECTOR DE BRONCE "LUISE" DE 5 VIAS LUISE
CONECTOR DIRECTO SUBTERRANEO DE LATÓN MOD: DBC-BR PARA CONTROLADOR LOGIC PLUS - RAIN PRO
CONECTOR INICIAL + EMPAQUE 16 MM BILABIAL PE
CONECTOR INICIAL + EMPAQUE 20 MM
CONECTOR PE 4 MM
CONEXIONES DE 1/2" PVC VARIOS
CONEXIONES DE PVC Y CPVC Y FIERRO GALVANIZADO GLOBAL
CONEXIONES DE PVC Y F/G
CONEXIONES DE PVC Y TUBERÍA EN GENERAL
CONMUTADOR 1 - 0 
CONMUTADOR 1 - 0 -2
CONO DE SEGURIDAD
CONTACTOR
CONTACTOR
CONTACTOR 12 A
CONTACTOR 9 A
CONTACTOR DE 12 A
CONTACTOR DE 12 A - SCHNEIDER
CONTACTOR DE 12 AMPERIOS
CONTADOR VOLUMÉTRICO DE AGUA DE 2" TIPO MOLINETE TECNIDROMONDRAGON
CONTROLADOR DE 1 ESTACIÓN A BATERIA 400A-000
CONTROLADOR DE 6 ESTACIONES GQ-AC6
CONTROLADOR DE 8 ESTACIONES GQ-AC8
CONTROLADOR DE RIEGO DE 1 A 16 ESTACIONES - P2 (PRO-TWO CONTROLLER)
CONTROLADOR DE RIEGO DE 1 -A 16 ESTACIONES P2
CONTROLADOR DE RIEGO DE 1 A 42 ESTACIONES MOD: LP42S-C (LOGIC PLUS)
CONTROLADOR DE RIEGO DE 1 ESTACIÓN A BATERIA               MOD:400A-000
CONTROLADOR DE RIEGO DE 1 ESTACIÓN A BATERÍA - ORBIT
CONTROLADOR DE RIEGO DE 1 ESTACIÓN A BATERIA MOD: BOCS - RAIN PRO
CONTROLADOR DE RIEGO DE 1 ESTACIÓN A BATERIA SVC - HUNTER
CONTROLADOR DE RIEGO DE 3 ESTACIONES MOD: RP-XC-315S EXPANDIBLE HASTA 15 ESTACIONES CON MÓDULO DE EXPANSIÓN - RAIN PRO
CONTROLADOR DE RIEGO DE 4 ESTACIONES - Lawn Master II 4 Mod: 53805
CONTROLADOR DE RIEGO DE 4 ESTACIONES - LEGO
CONTROLADOR DE RIEGO DE 4 ESTACIONES  XC-401i
CONTROLADOR DE RIEGO DE 4 ESTACIONES MOD: HDC4-S - RAIN PRO.
CONTROLADOR DE RIEGO DE 4 ESTACIONES XC-401i
CONTROLADOR DE RIEGO DE 6 ESTACIONES  XC-601i
CONTROLADOR DE RIEGO DE 6 ESTACIONES MOD: GQ-AC6
CONTROLADOR DE RIEGO DE 6 ESTACIONES MOD: HDC6-S - RAIN PRO.
CONTROLADOR DE RIEGO DE 6 ESTACIONES XC-601i  
CONTROLADOR DE RIEGO DE 8 ESTACIONES  XC-801i
CONTROLADOR DE RIEGO DE 8 ESTACIONES MOD: GQ-AC8
CONTROLADOR DE RIEGO DE 8 ESTACIONES XC-801i 
CONVERTOR UNIVERSAL MOD: LP-UNI-2S DE 40 ESTACIONES (CONVIERTE CUALQUIER CONTROLADOR EN SISTEMA DE 2 HILOS) - RAIN PRO.
CORTADOR DE CONCRETO CON MOTOR HONDA DE 13 HP
CURVA DE 1" LUZ SEL
CURVA DE 3/4" LUZ
CURVA DE 3/4" LUZ SEL
CUSTODIA ARMADA
DECODIFICADOR PROGRAMABLE (P2-D) PARA CONTROLADOR P2
DECODIFICADOR PROGRAMABLE P2-D PARA CONTROLADOR P2
DESCARGA
DESNATADOR DE 8" 
DIFUSOR BAILARINA NEGRA DE MICOASPERSOR
DIFUSOR DE 1/2" HPO4 - RAIN PRO
DIFUSOR DE 1/2" POP-UP MOD: 904F (HEMBRA) - RAIN PRO
DIFUSOR DE 1/2" PROS-04
DIFUSOR DE 1/2" PROS-04   HUNTER
DIFUSOR ROJO DE 180° PARA MICROASPERSOR
DISCO DE CORTE CONCRETO 30-45 CM
DISCO DE CORTE PARA CONCRETO
DISCO DIAMANTADO
DISCO DURO TOSHIBA P300, 1 TB, SATA 6.0 Gb/S 7200 RPM 3.5"
DISPOSITIVO DE GPS - CAMIONETA NUEVA
DOC DE TARUGOS
DOC DE TORNILLOAUTOROSCANTE 8 X 58
DOC DE TORNILLOS SPACK
DOC TARUGO AZUL
DOMBUSTIBLE
DVD SUPERMULTI LG
ELECTROBOMBA CENTRÍFUGA DE DOBLE IMPULSOR DE 1.5 Hp TRIFÁSICA 220V/60Hz. MOD: 25-140/11T
ELECTROBOMBA CENTRÍFUGA DE DOBLE IMPULSOR DE 2.0 Hp TRIFÁSICA 220V/60Hz. MOD: 25-160/15T
ELECTROBOMBA CENTRÍFUGA DE DOBLE IMPULSOR DE 3.0 Hp TRIFÁSICA 220V/60Hz. MOD: 25-160/22T
ELECTROBOMBA CENTRÍFUGA DE DOBLE IMPULSOR DE 4.0 Hp TRIFÁSICA 220V/60Hz. MOD: 232-200/30T
ELECTROBOMBA CENTRÍFUGA DOBLE IMPULSOR DE 1.5 Hp TRIFÁSICO 220V/60Hz MOD: 25-140/11T 
ELECTROBOMBA CENTRÍFUGA DOBLE IMPULSOR DE 2.0 Hp TRIFÁSICO 220V/60Hz MOD: 25-160/15T 
ELECTROBOMBA CENTRÍFUGA DOBLE IMPULSOR DE 3.0 Hp TRIFÁSICO 220V/60Hz MOD: P2C 25-160/22 
ELECTROBOMBA CENTRÍFUGA DOBLE IMPULSOR DE 4.0 Hp TRIFÁSICO 220V/60Hz MOD: P2C 32-200/30 
ELECTROBOMBA CENTRÍFUGA DOBLE IMPULSOR DE 5.5 Hp TRIFÁSICO 220V/60Hz MOD: P2C 32-400/40 
ELECTROBOMBA CENTRÍFUGA DOBLE IMPULSOR DE 5.5 Hp TRIFÁSICO 220V/60Hz MOD: PST65-125/40 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONAL DE 1.0 Hp MONOFÁSICO 220V/60Hz MOD: CHLF 2-30 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONAL DE 1.0 Hp TRIFÁSICO 220V/60Hz MOD: CHLF 2-30 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONAL DE 1.5 Hp MONOFÁSICO 220V/60Hz MOD: CHLF 4-30 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONAL DE 1.5 Hp TRIFÁSICO 220V/60Hz MOD: CHLF 4-30 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONAL DE 2.0 Hp TRIFÁSICO 220V/60Hz MOD: CHLF 4-4 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONAL DE 3.0 Hp TRIFÁSICO 220V/60Hz MOD: CHLF(T)8-30 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONTAL DE 1.0 Hp MONOFÁSICA 220V/60Hz. MOD: CHLF 2-30
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS HORIZONTAL DE 1.5 Hp MONOFÁSICA 220V/60Hz. MOD: CHLF 4-30
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS VERTICAL DE 1.5 Hp TRIFÁSICO 220V/60Hz MOD: PV 4 X 4/1.5 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS VERTICAL DE 2.0 Hp TRIFÁSICO 220V/60Hz MOD: PV 4 X 6/2 
ELECTROBOMBA CENTRÍFUGA MULTIETAPAS VERTICAL DE 3.0 Hp TRIFÁSICO 220V/60Hz MOD: PV 4 X 8/3 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 1.0 Hp MONOFÁSICO 220V/60Hz MOD: PC 5B 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 1.5 Hp MONOFÁSICO 220V/60Hz MOD: PC 5BM 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 1.5 Hp TRIFÁSICO 220V/60Hz MOD: PC 5BM 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 10.0 Hp TRIFÁSICA /60Hz VOLTAJE DUAL 220/380V MOD: PC-680A
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 10.0 Hp TRIFÁSICO VOLTAJE DUAL 220V/380V/60Hz MOD: PC 680A 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 2.0 Hp TRIFÁSICO 220V/60Hz MOD: PC 5AM 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 3.0 Hp TRIFÁSICO 220V/60Hz MOD: PC 220C 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 5.5 Hp TRIFÁSICO 220V/60Hz MOD: PC 680C 
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 7.5 Hp TRIFÁSICA /60Hz VOLTAJE DUAL 220/380V MOD: PC-680B
ELECTROBOMBA CENTRÍFUGA ROSCADA DE 7.5 Hp TRIFÁSICO VOLTAJE DUAL 220V/380V/60Hz MOD: PC 680B 
ELECTROBOMBA DE DRENAJE SUMERGIBLE DE 0.25 Hp MONOFÁSICA 220V/60Hz MOD: SPA5-10-0.25F CON FLOTADOR
ELECTROBOMBA DE DRENAJE SUMERGIBLE DE 0.5 Hp MONOFÁSICA 220V/60Hz MOD: SPA370F CON FLOTADOR
ELECTROBOMBA DE DRENAJE SUMERGIBLE DE 0.75 Hp MONOFÁSICA 220V/60Hz MOD: SPA550F CON FLOTADOR
ELECTROBOMBA DE DRENAJE SUMERGIBLE DE 1.0 Hp MONOFÁSICA 220V/60Hz MOD: SPA6-18-0.75F CON FLOTADOR
ELECTROBOMBA DE DRENAJE SUMERGIBLE DE 1.5 Hp MONOFÁSICA 220V/60Hz MOD: SPA1100F CON FLOTADOR
ELECTROBOMBA DE DRENAJE SUMERGIBLE DE 1.5 Hp MONOFÁSICA 220V/60Hz MOD: SPA2-60/6-1.1F CON FLOTADOR
ELECTROBOMBA FAMAC F15V -A-BL-15 CV- DE 15 HP TRIF
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 0.5 Hp MONOFÁSICA 220V/60Hz MOD: SMP50
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 0.5 Hp MONOFÁSICO 220V/60Hz MOD: SMP50
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 0.75 Hp MONOFÁSICA 220V/60Hz MOD: SUPB075
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 0.75 Hp MONOFÁSICO 220V/60Hz MOD: SUPB075
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 1.0 Hp MONOFÁSICA 220V/60Hz MOD: SCPB100
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 1.0 Hp MONOFÁSICO 220V/60Hz MOD: SCPB100
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 1.5 Hp MONOFÁSICA 220V/60Hz MOD: SCPB150
ELECTROBOMBA PARA RECIRCULACIÓN DE PISCINA DE 1.5 Hp MONOFÁSICO 220V/60Hz MOD: SCPB150
ELECTROBOMBA SUMERGIBLE DE DRENAJE DE 0.33 Hp MONOFÁSICO 220V/60Hz MOD: SPA5-10-0.25F CON INTERRUPTOR DE FLOTACIÓN
ELECTROBOMBA SUMERGIBLE DE DRENAJE DE 0.5 Hp MONOFÁSICO 220V/60Hz MOD: SPA370F CON INTERRUPTOR DE FLOTACIÓN
ELECTROBOMBA SUMERGIBLE DE DRENAJE DE 0.75 Hp MONOFÁSICO 220V/60Hz MOD: SPA550F CON INTERRUPTOR DE FLOTACIÓN
ELECTROBOMBA SUMERGIBLE DE DRENAJE DE 1.0 Hp MONOFÁSICO 220V/60Hz MOD: SPA6-18-0.75F CON INTERRUPTOR DE FLOTACIÓN
ELECTROBOMBA SUMERGIBLE DE DRENAJE DE 1.5 Hp MONOFÁSICO 220V/60Hz MOD: SPA1100F CON INTERRUPTOR DE FLOTACIÓN
ELECTROBOMBA SUMERGIBLE DE DRENAJE DE 1.5 Hp MONOFÁSICO 220V/60Hz MOD: SPA2-60/6-1.1F CON INTERRUPTOR DE FLOTACIÓN
ELECTROBOMBA SUMERGIBLE TIPO LAPICERO DE 1.0 Hp TRIFÁSICO  220V/60Hz MOD: 100QJ1003-0.75
ELECTROBOMBA SUMERGIBLE TIPO LAPICERO DE 1.5 Hp TRIFÁSICO  220V/60Hz MOD: 100QJ1005-1.1.
ELECTROBOMBA SUMERGIBLE TIPO LAPICERO DE 5.5 Hp TRIFÁSICO  220V/60Hz MOD: 100QJ815-4.0.
ELECTROVÁLVULA DE 1 1/2" CO CONTROL DE FLUJO 515-050
ELECTROVÁLVULA DE 1 1/2" MOD: 215-050 (PLOMO) CON REGULADOR DE CAUDAL - RAIN PRO
ELECTROVÁLVULA DE 1 1/2" MOD: 515-050 (NEGRO) CON REGULADOR DE CAUDAL - RAIN PRO
ELECTROVÁLVULA DE 1" (25 MM) CON CONTROL DE CAUDAL     MOD: PGV-101G(C/R HEMBRA) - HUNTER
ELECTROVÁLVULA DE 1" (25 MM) SIN CONTROL DE CAUDAL       MOD: PGV-100G(C/R HEMBRA) - HUNTER
ELECTROVÁLVULA DE 1" CON CONTROL DE FLUJO 210-050
ELECTROVÁLVULA DE 1" MOD: 210-050 (PLOMO) CON REGULADOR DE CAUDAL - RAIN PRO
ELECTROVÁLVULA DE 1" MOD: 210-055 (A PRESIÓN) PLOMO         RAIN PRO
ELECTROVÁLVULA DE 1" MOD: 8410 (PLOMO) JAR TOP - RAIN PRO
ELECTROVÁLVULA DE 1" PGV-100G SIN REGULADOR DE FLUJO
ELECTROVÁLVULA DE 1" PGV-101G CON REGULADOR DE FLUJO
ELECTROVÁLVULA DE 1"C/R CAUDAL ROSCA HEMBRA
ELECTROVÁLVULA DE 1"S/R CAUDAL ROSCA HEMBRA
ELECTROVÁLVULA DE 2" CON REGULADOR DE CAUDAL          MOD: 520-050 (NEGRO) RAIN PRO
ELECTROVÁLVULA DE 2" MOD: 220-050 (PLOMO) CON REGULADOR DE CAUDAL - RAIN PRO
ELECTROVÁLVULA DE 3" CON REGULADOR DE CAUDAL          MOD: 530-050 (NEGRO) RAIN PRO
ENCHUFE
ENLACE RECTO DE 32 MM
ENLACE RECTO PE DE 25 MM
ENLACE REDUCIDO PE DE 32 MM X 20 MM
ENLACE REDUCIDO PE DE 32 MM X 25 MM
ENLACE ROSCA HEMBRA 32 MM X 1" C/AZUL
ENLACE ROSCA HEMBRA 50 MM X 1 1/2 C/AZUL
ENLACE ROSCA MACHO DE 32 MM X 1"
ENLACE ROSCA MACHO DE 50 MM X 1 1/2" C/AZUL
ENPAQUE DE JEBE DE 5 MM
ESCALIMETRO
ESCOBILLA
ESMERIL ANGULAR
ESQUINERO DE METAL
ESTACA DE PLÁSTICO AMARILLO DE 1/2"
ESTACA DE ZINC DE 1/2"
ESTACA PARA MICROASPERSOR
ESTACIONAMIENTO
ESTANTE DE METAL
EXAMENES MÉDICOS PREOCUPACIONALES
EXTRACTOR DE 5"
EXTRACTOR DE POLEA DE 8" 
FELPUDO
FIERRO DE 1/2" X 9 MTS
FIJO INTERNET
FILTRO ACEITE - AMAROK
FILTRO ACEITE - FOTÓN
FILTRO AIRE - FOTÓN
FILTRO CARTUCHO C250
FILTRO DE 1 1/2" DE MALLA DE 120 MESH
FILTRO DE 1 1/2" EN "Y" DE MALLA DE 120 MESH MOD: WT-YS015-12 - RAIN PRO.
FILTRO DE 1" EN "Y" DE MALLA DE 120 MESH MOD: WT-YS010-12 - RAIN PRO.
FILTRO DE 2" EN "T" DE MALLA DE 120 MESH (AZUL) MOD:WT-TS020-12 - RAIN PRO
FILTRO DE 2" EN "Y" DE MALLA DE 120 MESH (AZUL) MOD:WT-YPS020-12 - RAIN PRO
FILTRO DE 2" EN "Y" DE MALLA DE 120 MESH (AZUL) MOD:WT-YS020-12 - RAIN PRO
FILTRO DE 3" EN "T" DE MALLA  DE 120 MESH WT-TS030M-12
FILTRO DE 3" EN "T" DE MALLA DE 120 MESH(AZUL) MOD: WT-TS030M-12 - RAIN PRO
FILTRO DE GRAVA MOD: WT-2HUA (DE 2 TANQUE HORIZONTAL) AUTOMÁTICO - RAIN PRO.
FILTRO ESPA FKB 550 6TP
FILTRO OBLICUO P/RENCIÓN DE IMPUREZA "Y"
FILTRO PARA PISCINA ESPA FKB550 6TP
FILTRO PARA TANQUE ROTOPLAST
FILTRO PE DE MALLA DE 1 1/2"
FILTRO PETROLEO - AMAROK
FILTRO PETROLEO - FOTÓN
FILTRO PRO SERIES C/VÁLVULA SUPERIOR S244T
FLETE MARÍTIMO
FLETE MARÍTIMO, SED, B/L
FLOTADOR DE 1" BRONCE
FOCO AHORRADOR
FOCO PARA REFLECTOR DE SPA
FOCO REPUESTO CAMIONETA
FORMADOR DE EMPAQUE 3H X 130 GR T/AVIAC. AZUL
FORMADOR DE EMPAQUETADURA ADEX 3-H P/USO AUTOMOTRIZ
FUENTE ANTRYX B500 V2 ATX 2.3 BOX
GABINETE
GABINETE DE  60 X 60 15
GABINETE DE 20 X 30
GABINETE DE 25 X 30
GABINETE DE 30 X 30
GABINETE DE 40 X 30
GABINETE METÁLICO 30 X 20 CM
GABINETE ROCKER 28 X 28 X 12
GALÓN DE ACEITE SUPER CUT 46 (CORTE Y MAQUINADO)
GALÓN DE PEGAMENTO THF ESPESO CEMENTO UNIVERSAL
GALÓN LIMPIA PARABRISAS
GASTO ADMINISTRATIVO
GASTO OPERATIVO DE PUERTO
GASTOS OPERATIVOS
GEOMEMBRANA PVC 0.75 MM NEGRO (SATEC)
GEOMEMBRANA PVC 1.00 MM NEGRO (SATEC)
GEOTEXTIL TNT 200 GR 3.00 X 100 MTS
GL PEAK 33%
GOTERO 4 L/H
GOTERO DE INSERCIÓN STRIMÓN AJUSTABLE DE 0-100 LPH VERDE
GOTERO DESMONTABLE 4 LPH
GOTERO DESMONTABLE PC  4 L/H RAMBO
GOTERO DESMONTABLE PC 2 LPH
GOTERO PC AUTOLIMPIANTE 4 L/H MICROFLAPPER
GOTERO PC Y AUTOLIMPIANTE 4 L/H MICROPLAPPER
GOTERO PE REGULABLE ROJO 0-70 L/H
GOTERO PE REGULABLE ROJO 0-70 L/H
GOTERO REGULABLE DE 0-70 L/H - ERHAS
GOTERO REGULABLE ROJO 0-70 L/H - AZUD
GOTEROS DE 6 SALIDAS
GUARDA MOTOR DE 4-6 - 6-10
GUARDAMOTOR 1 - 10 AMP
GUARDAMOTOR 4 - 6 AMP
GUARDAMOTOR 6 - 10 A
GUARDAMOTOR 6 - 10 AMP
GUARDAMOTOR DE 1-10 A
GUARDAMOTOR DE 2-5 AMP
GUARDAMOTOR DE 6 - 10 AMP
GUARDAMOTOR DE 7 - 10 AMP
GUARDAMOTOR DE 9 - 14 AMP
GUÍAS DE REMISIÓN REMITENTE
HALIZAN (250 Y 500 GR)
HANDLING
HANDLING // GASTOS ADMINISTRATIVOS
HIDROLINA Y LÍQUIDO DE FRENO
HOJA DE SIERRA
HOJA DE SIERRA
INSTALACIÓN DE SISTEMAS DE RIEGO TECNIFICADO
JUEGO DE CARBONES
JUEGO DE COMEDOR (8 SILLAS, BASE Y TABLERO)
JUEGO DE FRENO (CAMIONETA NEGRA)
JUEGO DE RODAJE Y SELLO
JUEGO DE SALA 3-2 BUTACA Y DECORACIÓN
JUEGO DE SUSPENSIÓN (AMORTIGUADORES, MUELLE Y RESORTE) FORD RANGER
KG DE CLORO EN PASTILLA
KG DE CLORO GRANULADO
KG DE MANGA DE RIEGO DE 4"
KG DE MICROTUBO PVC DE 4 MM (40 M X KG)
KG DE OCRE
KG DE SULFATO DE ALUMINIO
KG MICROTUBO PVC  3MM (60 MTS POR KG APROX)
KG MICROTUBO PVC DE 4 MM (40 MTS X KG APROX)
KG OCRE NEGRO
KING BLOCK 35 X 35
KIT AUTOMÁTICO DE PRESIÓN ESPA PRESSDRIVE AM NP
KIT BRIDA PARA ETERNIT
KIT DE ALARMA OFICINAS
KIT DE EMBRAGUE
KIT DE SEGURIDAD
LADRILLO Y PLAN TECHO
LAMPA RECTA BELLOTA
LAMPA TRAMANTINA
LAMPA Y PICO CON MAGO
LIMPIAPARABRISAS VISTONY GLN
LLANTA CON ARO
LLANTAS 245/75R16 DUNLOP AT (CAMIONETA AZUL)
LLAVE D PASO DE 1/2"
LLAVE DE PASO DE 1 1/2" 
LLAVE DE PASO DE 1 1/2" S/P
LLAVE DE PASO DE 1"
LLAVE DE PASO DE 1" C/R
LLAVE DE PASO DE 1/2"
LLAVE DE PASO DE 1/2" BRONCE
LLAVE DE PASO DE 1/2" C/R
LLAVE DE PASO DE 1/2" CIM
LLAVE DE PASO DE 1/2" S/P
LLAVE DE PASO DE 2" CIMVAL
LLAVE DE PASO DE 3/4" BRONCE
LLAVE MONOFÁSICO 2 X 20
LLAVE TÉMICA DE 25 AMP
LLAVE TÉRMICA
LLAVE TÉRMICA 2 X 16
LLAVE TÉRMICA 2 X 20 AMP
LLAVE TÉRMICA 2X20
LT DE HIDROLINA VEXTROM
M DE RIEL
M DE TUBO INOX C/R
M2 CERÁMICO
MACETA FIBRA DE VIDRIO CON PALMERA RAPHIS
MADERA Y MDF
MAGNÉTICO LIVIANO EFM SERV INSTALACIÓN
MAGNÉTICO LIVIANO SERVICIO DE MONITOREO
MANGUERA DE 16 MM C-2.5 2.2 LPH / GOTEROS INCORPORADOS A 0.50 M X 500
MANGUERA HDPE DE 1 1/2" (50 MM) C-10
MANGUERA LIVIANA 1.5" X 40 FT (12 MTS)
MANGUERA PE 16 MM C-4
MANGUERA PE 25 MM C-4
MANGUERA PE 32 MM C-4
MANGUERA PE DE 1" (32 MM) C-4
MANGUERA PE DE 16 MM C-2.5
MANGUERA PE DE 16 MM C-2.5 2.2 LPH / GOTEROS INCORPORADOS A 0.50 M X 500
MANÓMETRO
MANÓMETRO "LUISE" 0-6 BAR (0 - 88 PSI)
MANÓMETRO CON GLICERINA DE 0 -10 PSI
MANÓMETRO DE 2" SIN GLICERINA MOD: C5-LG100 - RAIN PRO
MANÓMETRO DE 2.5" CON GLICERINA MOD: C5-DG100 - RAIN PRO
MANTENIMIENTO CAMIONETA (FILTRO DE ACEITE, PETROLEO, AIRE) ACEITE
MANTENIMIENTO CAMIONETA VOLKSWAGEN
MANTENIMIENTO DE CAMIONETA AZUL (ALK-767) FILTRO DE ACEITE, PETROLEO, AIRE.
MANTENIMIENTO DE INYECTORES ELECTRONICOS (CAMIONETA AZUL)
MÁQUINA ROSCADORA DE 1/2" A 4" 
MASCARILLA
MEMORIA A-DATA 8GB DDR4 3000 MHz XPG GAMMIX
MEMORIA RAM DDR-3 DE 8 GB KINGSTON HYPERX FURY
METRO CÚBICO DE ARENA GRUESA
METROS CUADRADOS DE BONAGARDEN SMART 45 MM 14,400 (GRASS SINTETIC
METROS CUADRADOS DE GEOMEMBRANA PVC 0.75 MM NEGRO
METROS CUADRADOS DE GEOTEXTIL TNT 200 GR 3 X 100 MTS
METROS CUBICOS DE AGREGADOS
METROS CÚBICOS DE CONCRETO PREMEZCLADO BOMBEADO FC-210 HUSO 5/7 SLUMP 4" - 6"
METROS DE CABLE N° 10 (6 MM) THW-90
METROS DE CABLE N° 10 (6 MM) THW-90
METROS DE CABLE N° 12 TWF-90 12 AWG 750 V
METROS DE CABLE N° 14 THW-90 14 AWG 750 V
METROS DE CABLE N° 16 TWF-80 16 AWG 750 V
METROS DE CABLE N° 8 TWF-80 8 AWG 750 V
METROS DE CABLE VULCANIZADO N° 14 TTRF-70 2 X 14 AWG 500V
METROS DE CABLE VULCANIZADO TTRF-70 2X14 AWG 500 V
METROS DE CUERDA
METROS DE MANGUERA CORRUGADA
METROS DE MANGUERA DE 16 MM C-4
METROS DE MANGUERA DE 20 MM C-2.5
METROS DE MANGUERA PE 16 MM C-2.5
METROS DE MANGUERA PE 20 MM C-2.5
METROS DE MANGUERA PE 20 MM C-4
METROS DE MANGUERA PE DE 25 MM (3/4") C-4
METROS DE MANGUERA PE DE 32 MM
METROS DE MANGUERA PEBD 16 MM C-2.5
METROS DE MANGUERA PEBD 20 MM C-2.5
METROS DE MANGUERA PEBD DE 16 MM C-2.5
METROS DE MANGUERA PEBD DE 3/4" (25 MM) C-4
METROS DE TUBO INOX DE 2"
METROS MALLA AC. ACERO INOXIDABLE C-304 N° 140 X 1.00 M 0.06 MM ABERTURA 120 MI
MICHIGRASS
MICROJET SPRAY 180° ROJO NEGRO
MICROJET SPRAY 360° ROJO NEGRO
MICROTUBO PVC 4 MM
MICROTUBO PVC X 50 CM PARA MICROASPERSOR
MICROYET SPRAY 180° (ROJO/NEGRO) TECO
MILLAR DE TORNILLO 7 X 1
MOA
MODULO DE EXPANSIÓN DE 4 ESTACIONES MOD: RP-XC-4 PARA CONTROLADOR RP-XC-315S - RAIN PRO.
MONITOR SAMSUNG DE 24" PLS
MONITOREO ALARMA
MONITOREO DE CARGA SUELTA MERCADERIA GENERAL
MOTHERBOARD GIGABYTE Z370P DE DDR4, SATA 6.0 USB 3.1
MOVIL DELVAC 15W40 GL
MT2 DE GEOMEMBRANA DE PVC 0.75 MM NEGRO SATEC
MT2 DE GEOMEMBRANA DE PVC 1.00 MM NEGRO SATEC
NIPLE DE 1 1/2" X 2"
NIPLE DE 1 1/2" X 4"
NIPLE DE 1 1/2" X 4" PVC.
NIPLE DE 1 1/2" X 6"
NIPLE DE 1 1/4" X 1 1/2 F/G
NIPLE DE 1 1/4" X 2" AC. INOX C-304
NIPLE DE 1 1/4" X 2" F/G
NIPLE DE 1 1/4" X 2" INOX
NIPLE DE 1 1/4" X 3" AC. ACERO INOXIDABLE
NIPLE DE 1" X 1 1/2" AC. INOX C-304
NIPLE DE 1" X 1" INOX C-304
NIPLE DE 1" X 2" AC. INOX C-304
NIPLE DE 1" X 3"
NIPLE DE 1" X 3" AC. INOX C-304
NIPLE DE 1" X 4" AC. INOX C-304
NIPLE DE 1" X 4" PVC
NIPLE DE 1" X 4" PVC.
NIPLE DE 1" X 6"
NIPLE DE 1/2" X 2" AC.INOX C-304
NIPLE DE 1/2" X 3" ACERO INOXIDABLE C-304
NIPLE DE 1/2" X 4" PVC
NIPLE DE 1/2" X 4" PVC.
NIPLE DE 1/4" X 2"  
NIPLE DE 1/4" X 2" AC. INOX-304
NIPLE DE 1/4" X 2" ACERO INOXIDABLE C-304
NIPLE DE 2" X 2" ACERO INOXIDABLE C-304
NIPLE DE 2" X 3"
NIPLE DE 2" X 3" F/G
NIPLE DE 2" X 4" PVC
NIPLE DE 2" X 4" PVC.
NIPLE DE 2" X 5 ACERO
NIPLE DE 2" X 6" F/G
NIPLE DE 3/4" X 4" PVC
NIPLE DE 3/4" X 4" PVC.
NIPLE DE 3/4"" X 2" F/G
NIPLE DE 4" X 4" PVC
NIPLE DE 4" X 4" PVC
NIPLE GALVANIZADO DE 1 1/2" X 4" F/G
NIPLE PE DE 3/4"
NIPLES DE 1/2" X 4"
OCRE NEGRO BAYER 130
PABILO (OVILLO) X 40 GR DE ALGODÓN
PAPEL PARA PLOTTER
PAQUETE DE CINTILLO NEGRO 15 CM
PAR DE GUANTES
PARANTE DE 2 1/2"
PARANTE DE 3 5/8"
PARES DE BOTAS DE SEGURIDAD
PASAJE BUS
PEAJE
PEGAMENTO 1/32 AZUL
PEGAMENTO 1/32 DORADO
PEGAMENTO 1/4" DORADO
PEGAMENTO DE 1/32" AZUL - OATEY
PEGAMENTO DE 1/32" DORADO - OATEY
PEGAMENTO DE 1/4 AZUL
PEGAMENTO DE 1/4 DORADO
PEGAMENTO DE 1/4" AZUL - OATEY
PEGAMENTO DE 1/4" DORADO - OATEY
PEGAMENTO DE 1/8" AZUL
PEGAMENTO THF ESPESO 1 GALÓN
PERNO DE 5/8" X 2" C/T
PERNO EXAGONAL G-8 5/8 X 3" CON ARANDELA
PERNO ZINCADO 1/2" X 3" INC/ARANDELA, HUACHA PRESIÓN Y TUERCA
PICO CON MANGO PALA ANCHA
PICO DE LORO TRUPPER
PICO HERRAGRO CON MANGO
PICO PALA ANCHA
PICO PALA ANCHA C/MANGO
PILA BATERIA 9 V
PILOTO
PILOTO DE SEÑAL
PILOTO VERDE
PINTURA Y YESO CERÁMICO
PINTURAS VARIOS
PINZA AMPERIMÉTRICA UT-202
PLANCHA DE 1/2"
PLANCHA DE 3/4" DRYWALL
PLANCHA DE POLICARBONATO DE 6 MM
PLANCHA DE SUPER BOARD 4 MM
PLANTAS VARIOS
PLUMILLAS
POLIZA DE SEGURO
PONCHO DE 1 1/2" X 4" REBOTE
PONCHO DE 2" X 4" REBOTE
PORTA NIPLE CHUCK MOD RIDGID PARA ROSCADORA DE 1/2" A 2" USR PARA NIPLES DE 1/2"--3/4"--1"--1 1/4"--1 1/2" Y 2"
POTE GRASA MULTIUSO
PQTE DE PILAS X 4 UNIDADES
PRESOSTATO SQUARE
PRESS CONTROL AMARILLO
PROCESADOR INTEL CORE i7-8700, 3.20 Gzh, 12 MB CACHE LGA1151 65W14 Nm
PROGRAMADOR DE CAMPO PARA RECEPTORES LP-RP MOD. LP-HHRP - RAIN PRO
PROGRAMADOR DE RIEGO DE 1 ESTACIÓN A BATERIA
PUENTE PARA MICROASPERSOR
PUNTA EXAGONAL
PZA DE LLAVE P/CADENA
RADAR AUTOMÁTICO
RADIADOR MITSUBISHI L200 (DX-14136) - (CAMIONETA NEGRA)
RASTRILLO CON MANGO
RAYDER LÍQUIDO PARA RADIADOR
RECEPTOR PROGRAMABLE MOD:LP-RP PARA CONTROLADOR  LOGIC PLUS (LP) CONVERTOR UNIVERSAL (LP-UNI-2S) - RAIN PRO.
RECOGEDOR DE HOJAS DE PLÁSTICO
RECTÁNGULO 
REDUCCIÓN CAMPANA DE 1 1/2" X 1" INOX -316 C/R
REDUCCIÓN CAMPANA DE 1 1/4" X 1" INOX -316 C/R
REDUCCIÓN CAMPANA DE 2" X 1 1/4"  INOX-316 C/R
REDUCCIÓN CAMPANA DE 2" X 1 1/4" F/G
REDUCCIÓN CAMPANA DE 4" X 1 1/2" F/G
REDUCCIÓN DE 1 1/2" X 1 1/4" C/R
REDUCCIÓN DE 1 1/2" X 1 1/4" S/P
REDUCCIÓN DE 1 1/2" X 1 1/4" S/P.PVC
REDUCCIÓN DE 1 1/2" X 1" C/R
REDUCCIÓN DE 1 1/2" X 1" C/R.
REDUCCIÓN DE 1 1/2" X 1" S/P
REDUCCIÓN DE 1 1/2" X 1" S/P.
REDUCCIÓN DE 1 1/2" X 1/2" C/R
REDUCCIÓN DE 1 1/2" X 1/2" C/R.
REDUCCIÓN DE 1 1/2" X 1/2" S/P
REDUCCIÓN DE 1 1/2" X 3/4" C/R
REDUCCIÓN DE 1 1/2" X 3/4" C/R.
REDUCCIÓN DE 1 1/2" X 3/4" S/P
REDUCCIÓN DE 1" X 1/2" C/R
REDUCCIÓN DE 1" X 1/2" C/R. PVC
REDUCCIÓN DE 1" X 1/2" S/P
REDUCCIÓN DE 1" X 1/2" S/P AGUA
REDUCCIÓN DE 1" X 1/2" S/P PVC
REDUCCIÓN DE 1" X 1/2" S/P. PVC
REDUCCIÓN DE 1" X 3/4" C/R
REDUCCIÓN DE 1" X 3/4" C/R.
REDUCCIÓN DE 1" X 3/4" S/P
REDUCCIÓN DE 1" X 3/4" S/P
REDUCCIÓN DE 1" X 3/4" S/P.
REDUCCIÓN DE 1" X 3/4" S/P. PVC
REDUCCIÓN DE 2" X 1 1/2" C/R
REDUCCIÓN DE 2" X 1 1/2" C/R.
REDUCCIÓN DE 2" X 1 1/2" S/P
REDUCCIÓN DE 2" X 1 1/2" S/P.
REDUCCIÓN DE 2" X 1" C/R
REDUCCIÓN DE 2" X 1" C/R.
REDUCCIÓN DE 2" X 1" S/P
REDUCCIÓN DE 2" X 1" S/P.
REDUCCIÓN DE 2" X 1/2" C/R AGUA
REDUCCIÓN DE 2" X 1/2" C/R.
REDUCCIÓN DE 2" X 1/2" S/P
REDUCCIÓN DE 2" X 1/2" S/P.
REDUCCIÓN DE 2" X 3/4"
REDUCCIÓN DE 2" X 3/4" C/R AGUA
REDUCCIÓN DE 2" X 3/4" C/R.
REDUCCIÓN DE 2" X 3/4" S/P.
REDUCCIÓN DE 3" X 1 1/2" C/R
REDUCCIÓN DE 3" X 1 1/2" C/R.
REDUCCIÓN DE 3" X 2" C/R
REDUCCIÓN DE 3" X 2" C/R.
REDUCCIÓN DE 3" X 2" PVC
REDUCCIÓN DE 3" X 2" S/P.
REDUCCIÓN DE 3/4" X 1/2" C/R
REDUCCIÓN DE 3/4" X 1/2" C/R.
REDUCCIÓN DE 3/4" X 1/2" S/P
REDUCCIÓN DE 3/4" X 1/2" S/P AGUA
REDUCCIÓN DE 3/4" X 1/2" S/P. PVC
REDUCCIÓN DE 4" X 1 1/2" PVC
REDUCCIÓN DE 4" X 1 1/2" S/P PVC
REDUCCIÓN DE 4" X 2" S/P AGUA
REDUCCIÓN PE DENTADA 20 MM X 16 MM
REDUCCIÓN PE DENTADA 25 MM X 20 MM
REDUCCIÓN PVC  4" X 3" S/P C-10
REDUCCIÓNDE 1 X 1/2"
REFLECTOR DE 100 WATTS 12V
REFLECTOR DE 300 WATTS 12V
REFLECTOR DE LUZ HALÓGENA DE 300 W ACERO INOX
REFLECTOR DE LUZ INCANDESCENTE 300 W-12V (4.5 M) SP581S-15FT
REFLECTOR LUZ BLANCA LED 18 W - 12V
REFLECTOR LUZ INCANDESCENTE 300W-12V 15FT(4.5M)SP581S-15FT HAYWARD
REJILLA C/BASE 7 3/4" - 1.5 X 1.5"
RELAY 24 AC CON BASE
RELAY C/BASE
RELE DE 7 - 10  AMP
RELE DE 8 PINES
RELEI DE 9 A 13 APM
RELEI ENCAPSULADO 24 V AC + BASE
RELEI ENCAPSULADO AC/24V
RELEY ENCAPSULADO
RELEY ENCAPSULADO
RELEY TERMOENCENDIDO
REPUESTO CAMIONETA AZUL ( PASTILLA DE FRENO)
REPUESTO CAMIONETA NEGRA
REPUESTO CAMIONETA NEGRA PASTILLAS DE FRENO
REPUESTOS MAQUINA PODADORA DE CESPED
RESORTE DELANTERO HILUX
RESORTE SUSPENSIÓN TOY-HILUX ARGENTINO DELT (REPUESTO FOTOON)
RIEL
RIEL DE 2 1/2"
RIEL DE 3 5/8"
RIEL UNISTRAIG 41 X 2 X 1.5   2.4 METROS
ROCIADOR ÁNGULO REGULABLE 2"
ROCIADOR ANGULO REGULABLE DE 2" ORBIT
ROCIADOR POP-UP 1802
RODAJE 607 2RS/SKF
RODAJE 608 22/SKF
RODAJE 609 22/SKF
RODAJE 6202 2RS/SKF
RODAJE 6309
RODAJE 6507
ROLLO DE MANGUERA DE 3/4" REFORZADO X 100 MTS
ROLLO DE MANGUERA DE PE DE 16 MM C-2.5 DE 1.6LPH CON GOTEROS INCORPORADOS A 40 CM X 500 M
ROLLO DE MANGUERA REFORZADA HELIJARDIM ECO 1" X 50 MTS
ROLLO DE MANGUERA T/BOMBERO 2" 8-BAR C/ROJO X 100 MTS
ROLLO MANGUERA GEODRIP C-3500 CON GOTEROS A 40 CM - 0.9 MM/2 LPH X 400 M
ROMI 100
ROTOMARTILLO
ROTOR 1/2" SAM POP UP 3504 SECTORIAL
ROTOR DE 1" I-25
ROTOR DE 1" I-25 - HUNTER
ROTOR DE 1/2" POP-UP MOD- SERIE 3500 - RAIN BIRD
ROTOR DE 3/4" MOD: 5000
ROTOR DE 3/4" PGP-ADJ-B 
ROTOR DE 3/4" PGP-ADJ-B  - HUNTER
ROTOR DE 3/4" POP UP
ROTOR DE 3/4" POP-UP MOD: SERIE 5000 - RAIN BIRD
ROTOR PROFESIONAL DE 1/2" S 3500
SACO DE CUARZO 1/32"
SACO DE YESO BLANCO
SECADOR 32
SED
SEGURO COMPLEMENTARIO DE TRABAJO DE RIESGO PENSIONES
SEGURO COMPLEMENTARIO DE TRABAJO DE RIESGO SALUD
SEHLL RIMULA R5 E 10W40 GLN - FOTÓN
SELLO 560 7/8"
SEPARACIÓN DE ANDAMIOS
SERVICIO DE CARGA SUELTA MERCADERIA GENERAL
SERVICIO DE DESPACHO
SERVICIO DE REVISIÓN TÉCNICA
SERVICIO DE SELLADO/PEGADO DE GEOMEMBRANA
SERVICIO DE TRANSPORTE DE BIENES A CIENEGUILLA
SERVICIO EXTRAORDINARIO
SET DE BROCAS
SET DE FILTRO Y CARTUCHO
SILICONA
SILLA GIRATORIA
SMART POOL S601P CALENTADOR SOLAR
SMART POOL WWSK21, KIT PARA ENSAMBLAR CALENTADOR SOLAR
SOAT ALK-767
SOPORTE AMORTIGUADOR TOY-HILUX 2KD (REPUESTO FOTON)
SOPORTE DENTADO DE MICROASPERSOR
STOVE BOLTS M05 X 60 INOX-304 C/AV
SUPERVISIÓN CARGA SUELTA MERCADERIA GENERAL
TABLERO DE METAL
TALADRO INALAMBRICO
TANQUE DE AGUA DE 1100 LT 
TANQUE HIDRONEUMÁTICO DE 24 LTS
TANQUE PRESSUREWAVE 100 LTS VERTICAL (PWN100V) 150 PSI
TANQUE PRESSUREWAVE 100 LTS VERTICAL (PWN100V) 150 PSI
TANQUE PRESSUREWAVE 20 LTS HORIZONTAL (PWN20H) 150 PSI
TANQUE PRESSUREWAVE 20 LTS. HORIZOLTAL (PWN20H) 150 PSI
TANQUE PRESSUREWAVE 60 LTS VERTICAL (PWN60V) 150 PSI
TANQUE PRESSUREWAVE 60 LTS VERTICAL (PWN60V) 150 PSI
TANQUE ROTOPLAST 2500 LT
TAPÓN DE 1 1/2" C/R HEMBRA.
TAPÓN DE 1 1/2" C/R MACHO.
TAPÓN DE 1 1/2" S/P HEMBRA
TAPÓN DE 1 1/2" S/P HEMBRA - PAVCO
TAPÓN DE 1 1/2" S/P MACHO.
TAPÓN DE 1 1/4"
TAPÓN DE 1" C/R HEMBRA
TAPÓN DE 1" C/R HEMBRA.
TAPÓN DE 1" C/R MACHO.
TAPÓN DE 1" HEMBRA C/R
TAPÓN DE 1" HEMBRA S/P
TAPÓN DE 1" MACHO INOX
TAPÓN DE 1" S/P HEMBRA
TAPÓN DE 1" S/P HEMBRA -PAVCO
TAPÓN DE 1" S/P MACHO.
TAPÓN DE 1/2" C/R HEMBRA
TAPÓN DE 1/2" C/R HEMBRA.
TAPÓN DE 1/2" C/R MACHO.
TAPÓN DE 1/2" S/P HEMBRA
TAPÓN DE 1/2" S/P HEMBRA.
TAPÓN DE 1/2" S/P MACHO.
TAPÓN DE 2" F/G
TAPÓN DE 3/4" C/R HEMBRA
TAPÓN DE 3/4" C/R HEMBRA - PAVCO
TAPÓN DE 3/4" C/R MACHO.
TAPÓN DE 3/4" S/P HEMBRA
TAPÓN DE 3/4" S/P HEMBRA.
TAPÓN DE 3/4" S/P MACHO.
TAPÓN HEMBRA DE 1" S/P AGUA
TAPÓN HEMBRA DE 3/4" S/P AGUA
TAPÓN MACHO DE 1 1/2" F/G
TAPÓN MACHO DE 1" C/R INOX C-316.
TAPÓN MACHO DE 1" F/G
TAPÓN MACHO DE 1" INOX 304 C/R
TAPONES DE 1/2" Y ACCESORIOS DE F/G
TARUGO + TORNILO
TARUGOS
TARUGOS CON TORNILLOS
TECHO PERFORADO
TECLE PARA 2 TONELADAS
TEE DE 1 1/2" ACERO INOXIDABLE
TEE DE 1 1/2" C/R AGUA - PAVCO.
TEE DE 1 1/2" C/R AGUA.
TEE DE 1 1/2" F/G
TEE DE 1 1/2" S/P AGUA
TEE DE 1 1/2" S/P AGUA
TEE DE 1 1/2" S/P AGUA - PAVCO.
TEE DE 1 1/2" S/P AGUA.
TEE DE 1 1/4" ACERO  INOXIDABLE
TEE DE 1" C/R AGUA - PAVCO.
TEE DE 1" C/R AGUA.
TEE DE 1" INOX C-316 C/R
TEE DE 1" S/P AGUA
TEE DE 1" S/P AGUA
TEE DE 1" S/P AGUA - PAVCO.
TEE DE 1" S/P AGUA. INYECTOPLAST
TEE DE 1/2" C/R AGUA - PAVCO.
TEE DE 1/2" C/R AGUA PVC.
TEE DE 1/2" INOX C-316 C/R
TEE DE 1/2" S/P AGUA
TEE DE 1/2" S/P AGUA
TEE DE 1/2" S/P AGUA PAVCO.
TEE DE 1/2" S/P AGUA PVC.
TEE DE 2" C/R AGUA - PAVCO.
TEE DE 2" C/R AGUA.
TEE DE 2" DESAGUE
TEE DE 2" F/G
TEE DE 2" INOX C-304 C/R
TEE DE 2" S/P
TEE DE 2" S/P AGUA
TEE DE 2" S/P AGUA - PAVCO.
TEE DE 2" S/P AGUA.
TEE DE 20 X 20 X 20 CENTADA
TEE DE 3" C/R AGUA.
TEE DE 3" S/P AGUA
TEE DE 3" S/P AGUA - PAVCO.
TEE DE 3" S/P AGUA PVC.
TEE DE 3/4" C/R AGUA - PAVCO
TEE DE 3/4" C/R PVC AGUA.
TEE DE 3/4" S/P AGUA
TEE DE 3/4" S/P AGUA
TEE DE 3/4" S/P AGUA
TEE DE 3/4" S/P AGUA - PAVCO
TEE DE 3/4" S/P PVC AGUA.
TEE DE 4" DESAGUE
TEE DE 4" S/P AGUA
TEE DE 4" X 4" DESAGUE
TEE PE 25 MM X 1" X 25 MM C/AZUL
TEE PE 32 MM X 1" X 32 MM C/AZUL
TEE PE DE 16 MM DENTADA
TEE PE DE 20 MM DENTADA
TEE PE DE 25 MM DENTADA
TEE PE DE 25 MM MANGUERA MANGUERA
TEE PE DE 32 MM MANGUERA MANGUERA
TEE PE DE 32 MM X 1" X 32 MM C/NEGRO
TEE PE DE 32 MM X 3/4" X 32 MM
TEE PE DENTADA 16 MM
TEE PE DENTADA DE 16 MM
TEE PE DENTADA DE 25 MM
TEE RECTA DE 4" DESAGUE
TEE SANITARIA DE 4" DESAGUE
TEFLÓN
TELEDESPACHO
TERMA
TERMINAL CABLE ELECTRICO
TERMINAL DE LINEA DE 16 MM
TERMINAL DE LINEA DE 20 MM
TERMOSTATO 82° (REPUESTO CAMIONETA)
TEST DE PRUEBA
TIJERA DE PODAR DE MANO (PEQUEÑO)
TIJERA DE PODAR GRANDE
TIMER ANALÓGICO - GE
TIMER ANALÓGICO GENERAL
TIMER GE ANALÓGICO
TIMER GENERAL ELECTRIC ANALÓGICO
TIMMER
TIMMER ANALÓGICO GE
TINTA PARA IMPRESORA 02
TOMA
TOMA DOBLE DOMINOESENCIA
TOMACORRIENTE
TOMACORRIENTE BTICINO OVAL
TOMACORRIENTE VETE
TONER HP LASERJET CF283X M225 BLACK 2200 PAG
TORNILLO DE CALAMINA
TORNILLO P/REJILLA
TORNILLO P/REJILLA
TORNILLOS
TRAMPA DE 2" C/REGISTRO INYECTADO
TRANSFORMADOR DE 220-110 VOL
TRANSFORMADOR DE 250 WATTS
TRANSFORMADOR DE 350 W-220-14V
TRANSFORMADOR DE 50 W
TRANSFORMADOR DE 750 WATTS
TRANSMISIÓN // VISTO BUENO
TRÍPODE DE 1" METAL ZINCADO C/ELEVADOR X 75 CM
TUBERÍA DE 160 EXTRA POLITUBO
TUBERÍA DE 160 S-25 POLITUBO
TUBERÍA DE 4" ESTRA POLITUBO
TUBO CORRUGADO
TUBO DE  1 1/2" X 5 MTS S/P C-10 AGUA
TUBO DE 1 1/2" X 5 MTS C/R - TUBOPLAST (PESADO).
TUBO DE 1 1/2" X 5 MTS C/R AGUA
TUBO DE 1 1/2" X 5 MTS S/P C-10 - TUBOPLAST.
TUBO DE 1 1/2" X 5 MTS S/P C-10 AGUA
TUBO DE 1 1/2" X 5 MTS S/P C-10 AGUA
TUBO DE 1 1/4" X 5 MTS S/P C-10 AGUA
TUBO DE 1" X 3 MTS LUZ SEL
TUBO DE 1" X 3 MTS LUZ SEL
TUBO DE 1" X 5 MTS C/R - TUBOPLAST (PESADO).
TUBO DE 1" X 5 MTS C/R AGUA
TUBO DE 1" X 5 MTS C/R AGUA
TUBO DE 1" X 5 MTS S/P C-10 - TUBOPLAST.
TUBO DE 1" X 5 MTS S/P C-10 AGUA
TUBO DE 1" X 5 MTS S/P C-10 AGUA
TUBO DE 1" X 5 MTS S/P C-10 AGUA
TUBO DE 1/2" X 5 MTS C/R AGUA
TUBO DE 1/2" X 5 MTS C/R -TUBOPLAST (PESADO).
TUBO DE 1/2" X 5 MTS CPVC
TUBO DE 1/2" X 5 MTS S/P C-10 AGUA
TUBO DE 1/2" X 5 MTS S/P C-10 -TUBOPLAST.
TUBO DE 2" X 3 MTS DESAGUE
TUBO DE 2" X 5 MTS C/R - TUBOPLAST (PESADO).
TUBO DE 2" X 5 MTS C/R AGUA
TUBO DE 2" X 5 MTS S/P C-10 - TUBOPLAST.
TUBO DE 2" X 5 MTS S/P C-10 AGUA
TUBO DE 2" X 5 MTS S/P C-7.5 - TUBOPLAST.
TUBO DE 2" X 5 MTS S/P C-7.5 AGUA
TUBO DE 2" X 6 MTS FIERRO NEGRO
TUBO DE 3" X 3 MTS DESAGUE
TUBO DE 3" X 5 MTS S/P C-10 - TUBOPLAST.
TUBO DE 3" X 5 MTS S/P C-10 AGUA
TUBO DE 3" X 5 MTS S/P C-7.5 - TUBOPLAST.
TUBO DE 3" X 5 MTS S/P C-7.5 AGUA
TUBO DE 3/4" X 3 MTS LUZ - SEL - TUBOPLAST
TUBO DE 3/4" X 3 MTS LUZ SEL
TUBO DE 3/4" X 3 MTS LUZ SEL
TUBO DE 3/4" X 3 MTS LUZ SEL
TUBO DE 3/4" X 5 MTS C/R - TUBOPLAST (PESADO).
TUBO DE 3/4" X 5 MTS C/R AGUA
TUBO DE 3/4" X 5 MTS S/P C-10 - TUBOPLAST.
TUBO DE 3/4" X 5 MTS S/P C-10 AGUA
TUBO DE 3/4" X 5 MTS S/P C-10 AGUA
TUBO DE 4" X 3 MTS DESAGUE
TUBO DE 4" X 5 MTS  C-7.5 S/P
TUBO DE 4" X 5 MTS S/P AGUA
TUBO DE 6" LIVIANO DESAGUE
TUBO DE DE 1" X 5 MTS C/R AGUA
TUBO DE DE 1/2" X 5 MTS C/R AGUA
TUBO DE DE 3/4" X 5 MTS C/R AGUA
TUBO FLEX
TUBO TELESCÓPICO 12´ - 24´PESADO (3.66 A 7.32 MTS) GL-1224
TUERCA HEAGONAL G-8 5/8"
TV DE 55 PULGADAS SONY
UNIÓN 4" S/P AGUA
UNIÓN DE  1 1/2" S/P AGUA
UNIÓN DE 1 1/2" C/R.
UNIÓN DE 1 1/2" MIXTA.
UNIÓN DE 1 1/2" S/P AGUA
UNIÓN DE 1 1/2" S/P.
UNIÓN DE 1" C/R
UNIÓN DE 1" C/R.
UNIÓN DE 1" MIXTA
UNIÓN DE 1" MIXTA.
UNIÓN DE 1" MIXTO
UNIÓN DE 1" S/P
UNIÓN DE 1" S/P AGUA
UNIÓN DE 1" S/P.
UNIÓN DE 1/2" C/R
UNIÓN DE 1/2" C/R.
UNIÓN DE 1/2" MIXTA. PVC
UNIÓN DE 1/2" MIXTO
UNIÓN DE 1/2" S/P AGUA
UNIÓN DE 1/2" S/P AGUA
UNIÓN DE 1/2" S/P.
UNIÓN DE 2" C/R.
UNIÓN DE 2" F/G
UNIÓN DE 2" S/P AGUA
UNIÓN DE 2" S/P AGUA
UNIÓN DE 3" S/P MATUSITA
UNIÓN DE 3/4" C/R AGUA
UNIÓN DE 3/4" C/R.
UNIÓN DE 3/4" MIXTA.
UNIÓN DE 3/4" MIXTO
UNIÓN DE 3/4" S/P AGUA
UNIÓN DE 3/4" S/P AGUA
UNIÓN DE 3/4" S/P.
UNIÓN DROYZER DE 75 MM
UNIÓN MIXTA DE 1/2
UNIÓN PE 1" R/H
UNIÓN PE DE 3/4" R/H
UNIÓN PE DENTADO 20 MM
UNIÓN PE DENTADO 32 MM
UNIÓN PE DENTADO DE 16 MM
UNIÓN PE DENTADO DE 20 MM
UNIÓN PE DENTADO DE 25 MM
UNIÓN PE DENTADO DE 32 MM
UNIÓN SIMPLE DE 1" INOX-316 C/R
UNIÓN SIMPLE DE 1/4" INOX 316 C/R
UNIÓN SIMPLE DE 2" INOX-316 C/R
UNIÓN UNIVERSAL DE 1 1 /2" F/G
UNIÓN UNIVERSAL DE 1 1/2"
UNIÓN UNIVERSAL DE 1 1/2" C/R
UNIÓN UNIVERSAL DE 1 1/2" C/R.
UNIÓN UNIVERSAL DE 1 1/2" F/G
UNIÓN UNIVERSAL DE 1 1/2" S/P
UNIÓN UNIVERSAL DE 1 1/2" S/P.
UNIÓN UNIVERSAL DE 1 1/4" C/R
UNIÓN UNIVERSAL DE 1 1/4" INOX-316 C/R
UNIÓN UNIVERSAL DE 1" C/R
UNIÓN UNIVERSAL DE 1" C/R.
UNIÓN UNIVERSAL DE 1" INOX-316 C/R
UNIÓN UNIVERSAL DE 1" PVC C/R
UNIÓN UNIVERSAL DE 1" S/P
UNIÓN UNIVERSAL DE 1" S/P.
UNIÓN UNIVERSAL DE 1/2" C/R
UNIÓN UNIVERSAL DE 1/2" C/R.
UNIÓN UNIVERSAL DE 1/2" S/P
UNIÓN UNIVERSAL DE 1/2" S/P.
UNIÓN UNIVERSAL DE 2" C/R
UNIÓN UNIVERSAL DE 2" C/R.
UNIÓN UNIVERSAL DE 2" F/G
UNIÓN UNIVERSAL DE 2" INOX-304 C/R
UNIÓN UNIVERSAL DE 2" S/P
UNIÓN UNIVERSAL DE 2" S/P.
UNIÓN UNIVERSAL DE 3" C/R
UNIÓN UNIVERSAL DE 3/4" C/R
UNIÓN UNIVERSAL DE 3/4" C/R.
UNIÓN UNIVERSAL DE 3/4" S/P
UNIÓN UNIVERSAL DE 3/4" S/P.
UNIÓN UNIVERSAL DE 4" C/R PVC
UNIÓN UNIVERSAL DE 4" C/R PVC
UTILES DE OFICINA
VÁLVULA CHECK ANTIDRENAJE PARA DIFUSOR DE 1/2" PROS-04
VÁLVULA CHECK ANTIDRENAJE PARA DIFUSOR DE 1/2" PROS-04 MOD: 437-400 - HUNTER
VÁLVULA CHECK DE 1 1/2" DE PALETA
VÁLVULA CHECK DE 1 1/2" VERT/HORI C/RESORTE
VÁLVULA CHECK DE 1" DE PALETA
VÁLVULA CHECK DE 1/2"
VÁLVULA CHECK DE 2"
VÁLVULA CHECK DE 2" SWIN INOX C-316 200WOG
VÁLVULA CHECK DE 3"  VERTICAL CANASTILLA 
VÁLVULA CHECK DE 3/4" CIMVALL
VÁLVULA CHECK DE 3/4" DE PALETA
VÁLVULA CHECK DE PALETA DE 1.5" C/UU 1720-15C CUSTOM
VÁLVULA CHECK DE PALETA DE 2" C/UU 1720-20C CUSTOM
VÁLVULA CHECK DE PIE DE "1 1/2"
VÁLVULA CHECK DE PIE DE 1 1/4"
VÁLVULA CHECK DE PIE DE 1"
VÁLVULA CHECK DE PIE DE 2"
VÁLVULA DE 1/2" CIMVAL
VÁLVULA DE 6 VÍAS LATERAL DE 1.5" SP0710 XALL HAYWARD
VÁLVULA DE 6 VIAS SUPERIOR DE 1.5" SP0714T + ABRAZADERA P/FILTRO PRO SERIES PVC
VÁLVULA DE ACOPLE RÁPIDO DE 1" PLST PROJECT
VÁLVULA DE PASO DE 1 1/2"
VÁLVULA DE PASO DE 1 1/2" S/P
VÁLVULA DE PASO DE 1"
VÁLVULA DE PASO DE 1" S/P
VÁLVULA DE PASO DE 1/2" KITZ
VÁLVULA DE PASO DE 1/2" S/P
VÁLVULA DE PASO DE 2"
VÁLVULA DE PASO DE 2" S/P
VÁLVULA DE PASO DE 3/4"
VÁLVULA DE PASO DE 3/4" S/P
VÁLVULA DE PIE DE 1 1/2"
VÁLVULA DE PIE DE 1"
VÁLVULA DE PIE DE 1" CHECK
VÁLVULA DE PIE DE 2" 
VÁLVULA ESFÉRICA DE 1"
VÁLVULA ESFÉRICA DE 1" BRONCE
VÁLVULA ESFÉRICA DE 1" INOX C-316 2C
VÁLVULA ESFÉRICA DE 1/2"
VÁLVULA ESFÉRICA DE 3" INOX C-316 2C
VÁLVULA ESFÉRICA DE 3/4"
VÁLVULA FLIPEN
VÁLVULA RAMAL 3/4" X 16 MM
VÁLVULA RAMAL DE 1/2" X 16 MM
VÁLVULA RAMAL MANGUERA MANGUERA 16 MM
VÁLVULA RAMAL MANGUERA MANGUERA 20 MM
VÁLVULA REDUCTORA DE PRESIÓN DE 1" 143-1
VARIOS
VARIOS PANETON NAVIDAD
VINO PARA NAVIDAD
VISTO BUENO PORTUARIO
WINCHA DE 30 MTS, BOLSA DE CAL DE OBRA
WINCHA DE 5 MTS
YEE DE 4" DESAGUE
YEE DE 4" X 2" DESAGUE
YEE DE 4" X 2" DESAGUE`;

const lines = rawData.split('\n').map(l => l.trim()).filter(l => l);

function categorize(name) {
    const lower = name.toLowerCase();
    if (lower.includes('abrazadera') || lower.includes('adaptador') || lower.includes('codo') || lower.includes('buje') || lower.includes('bushing') || lower.includes('niple') || lower.includes('tee') || lower.includes('tubo') || lower.includes('tuberia') || lower.includes('union') || lower.includes('reducción') || lower.includes('tapon') || lower.includes('tapón')) {
        return 'Tuberías y Conexiones';
    }
    if (lower.includes('valvula') || lower.includes('válvula') || lower.includes('llave')) {
        return 'Válvulas';
    }
    if (lower.includes('electrobomba') || lower.includes('bomba') || lower.includes('cisterna') || lower.includes('tanque')) {
        return 'Electrobombas y Tanques';
    }
    if (lower.includes('aspersor') || lower.includes('microaspersor') || lower.includes('gotero') || lower.includes('rociador') || lower.includes('rotor') || lower.includes('boq') || lower.includes('manguera')) {
        return 'Sistemas de Riego';
    }
    if (lower.includes('cable') || lower.includes('caja') || lower.includes('contactor') || lower.includes('foco') || lower.includes('llave térmica') || lower.includes('transformador') || lower.includes('rele') || lower.includes('relay') || lower.includes('guardamotor') || lower.includes('controlador') || lower.includes('gabinete') || lower.includes('tomacorriente')) {
        return 'Accesorios Eléctricos';
    }
    if (lower.includes('filtro') || lower.includes('cartucho')) {
        return 'Filtros';
    }
    return 'Ferretería y Otros';
}

let sql = '-- Script de carga inicial para la tabla productos\n';
sql += 'INSERT INTO public.productos (nombre, categoria, precio, stock, imagen_url, descripcion) VALUES\n';

const values = lines.map(line => {
    const cat = categorize(line);
    const escapedName = line.replace(/'/g, "''");
    // default price 0, default stock 10, default image generic logo
    return `('${escapedName}', '${cat}', 0, 10, '/logo-eco-sistema.png', 'Producto de alta calidad')`;
});

sql += values.join(',\n') + ';\n';

fs.writeFileSync('seed.sql', sql);
console.log('seed.sql generated with ' + lines.length + ' products.');
