-- Borra filas de "productos" que NO son productos de catalogo: son gastos
-- internos, servicios, mantenimiento de vehiculos de la empresa y compras de
-- oficina que quedaron mezclados en el seed original (probablemente vinieron
-- de un export de gastos/compras, no de inventario real).
--
-- Categorias de lo que se borra: combustible/peajes/estacionamiento, fletes y
-- gastos de logistica portuaria, seguros (SCTR, poliza), mantenimiento y
-- repuestos de camionetas de la empresa, partes de computadora de oficina,
-- muebles de oficina, utiles de oficina.

delete from public.productos where id in (
  246, -- COMBUSTIBLE
  247, -- COMISIÓN
  297, -- CUSTODIA ARMADA
  300, -- DESCARGA
  311, -- DISCO DURO TOSHIBA P300...
  312, -- DISPOSITIVO DE GPS - CAMIONETA NUEVA
  317, -- DOMBUSTIBLE
  318, -- DVD SUPERMULTI LG
  407, -- ESTACIONAMIENTO
  409, -- EXAMENES MÉDICOS PREOCUPACIONALES
  414, -- FIJO INTERNET
  415, -- FILTRO ACEITE - AMAROK
  416, -- FILTRO ACEITE - FOTÓN
  417, -- FILTRO AIRE - FOTÓN
  433, -- FILTRO PETROLEO - AMAROK
  434, -- FILTRO PETROLEO - FOTÓN
  436, -- FLETE MARÍTIMO
  437, -- FLETE MARÍTIMO, SED, B/L
  441, -- FOCO REPUESTO CAMIONETA
  444, -- FUENTE ANTRYX B500 V2 ATX 2.3 BOX
  455, -- GALÓN LIMPIA PARABRISAS
  456, -- GASTO ADMINISTRATIVO
  457, -- GASTO OPERATIVO DE PUERTO
  458, -- GASTOS OPERATIVOS
  485, -- GUÍAS DE REMISIÓN REMITENTE
  487, -- HANDLING
  488, -- HANDLING // GASTOS ADMINISTRATIVOS
  489, -- HIDROLINA Y LÍQUIDO DE FRENO
  494, -- JUEGO DE COMEDOR (8 SILLAS, BASE Y TABLERO)
  495, -- JUEGO DE FRENO (CAMIONETA NEGRA)
  496, -- JUEGO DE RODAJE Y SELLO
  497, -- JUEGO DE SALA 3-2 BUTACA Y DECORACIÓN
  498, -- JUEGO DE SUSPENSIÓN (AMORTIGUADORES...) FORD RANGER
  511, -- KIT DE ALARMA OFICINAS
  512, -- KIT DE EMBRAGUE
  513, -- KIT DE SEGURIDAD
  518, -- LIMPIAPARABRISAS VISTONY GLN
  519, -- LLANTA CON ARO
  520, -- LLANTAS 245/75R16 DUNLOP AT (CAMIONETA AZUL)
  539, -- LT DE HIDROLINA VEXTROM
  546, -- MAGNÉTICO LIVIANO SERVICIO DE MONITOREO
  561, -- MANTENIMIENTO CAMIONETA (FILTRO DE ACEITE, PETROLEO, AIRE) ACEITE
  562, -- MANTENIMIENTO CAMIONETA VOLKSWAGEN
  563, -- MANTENIMIENTO DE CAMIONETA AZUL (ALK-767)...
  564, -- MANTENIMIENTO DE INYECTORES ELECTRONICOS (CAMIONETA AZUL)
  567, -- MEMORIA A-DATA 8GB DDR4...
  568, -- MEMORIA RAM DDR-3 DE 8 GB KINGSTON HYPERX FURY
  607, -- MONITOR SAMSUNG DE 24" PLS
  608, -- MONITOREO ALARMA
  609, -- MONITOREO DE CARGA SUELTA MERCADERIA GENERAL
  610, -- MOTHERBOARD GIGABYTE Z370P...
  611, -- MOVIL DELVAC 15W40 GL
  662, -- PASAJE BUS
  663, -- PEAJE
  696, -- POLIZA DE SEGURO
  704, -- PROCESADOR INTEL CORE i7-8700...
  711, -- RADIADOR MITSUBISHI L200 (CAMIONETA NEGRA)
  713, -- RAYDER LÍQUIDO PARA RADIADOR
  798, -- REPUESTO CAMIONETA AZUL (PASTILLA DE FRENO)
  799, -- REPUESTO CAMIONETA NEGRA
  800, -- REPUESTO CAMIONETA NEGRA PASTILLAS DE FRENO
  801, -- REPUESTOS MAQUINA PODADORA DE CESPED
  803, -- RESORTE SUSPENSIÓN TOY-HILUX ARGENTINO (REPUESTO FOTOON)
  838, -- SEGURO COMPLEMENTARIO DE TRABAJO DE RIESGO PENSIONES
  839, -- SEGURO COMPLEMENTARIO DE TRABAJO DE RIESGO SALUD
  847, -- SERVICIO DE TRANSPORTE DE BIENES A CIENEGUILLA
  852, -- SILLA GIRATORIA
  856, -- SOPORTE AMORTIGUADOR TOY-HILUX 2KD (REPUESTO FOTON)
  978, -- TERMOSTATO 82° (REPUESTO CAMIONETA)
  988, -- TINTA PARA IMPRESORA 02
  994, -- TONER HP LASERJET CF283X M225 BLACK 2200 PAG
  1143, -- UTILES DE OFICINA
  157  -- CASE GAMEMAX GAMING G505... (computadora, no riego/ferretería)
);
