-- Crear tabla 'clientes'
CREATE TABLE public.clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    logo_url text,
    orden integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS
-- Lectura pública para cualquier visitante de la web
CREATE POLICY "Permitir lectura publica de clientes" 
    ON public.clientes 
    FOR SELECT 
    USING (true);

-- Inserción, actualización y borrado solo para usuarios autenticados (Admin)
CREATE POLICY "Permitir insercion a administradores" 
    ON public.clientes 
    FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Permitir actualizacion a administradores" 
    ON public.clientes 
    FOR UPDATE 
    USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir borrado a administradores" 
    ON public.clientes 
    FOR DELETE 
    USING (auth.role() = 'authenticated');

-- Insertar los clientes actuales (fijos) para no perderlos
INSERT INTO public.clientes (nombre, orden) VALUES
('ACR Ingenieros & Arquitectos', 1),
('Arteco Inmobiliaria', 2),
('Desarrolladora', 3),
('Faber-Castell', 4),
('Garden Studio', 5),
('LMQ Lizette Miro Quesada', 6),
('Marcia Lenz Paisajismo', 7),
('Mall del Sur', 8),
('Markham College', 9),
('Playa del Sol', 10),
('Plaza Norte', 11),
('Vive PLM', 12),
('Martin Presentaciones', 13);
